services:
    glory.media.twig.extension.asset:
        class: Glory\Bundle\MediaBundle\Twig\Extension\AssetExtension
        arguments: [@service_container, @twig.extension.assets]
        tags:
            - { name: twig.extension }
